handlers =  java.util.logging.FileHandler

.level = INFO

java.util.logging.FileHandler.pattern = D:/JAVA MODULES 4/Lesson 10/java%u.log
java.util.logging.FileHandler.limit = 50000
java.util.logging.FileHandler.count = 5
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.FileHandler.append = true
java.util.logging.FileHandler.level = SEVERE